# Generated by Django 4.0.2 on 2022-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ns_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
    ]
