# Generated by Django 4.0.2 on 2022-03-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ns_user', '0004_profile_nickname_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
