# Generated by Django 4.0.2 on 2022-03-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': 'User', 'verbose_name_plural': '用户'},
        ),
    ]
