# Generated by Django 4.0.2 on 2022-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_game_gameid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='releasetime',
        ),
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='game',
            name='pic',
            field=models.ImageField(default='ns_game/None/no-img.jpg', upload_to='ns_game'),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
