# Generated by Django 4.0.2 on 2022-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_game_gameid_remove_game_releasetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default='2022-03-03 15:10[:10]'),
        ),
    ]
