# Generated by Django 4.0.2 on 2022-03-03 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
    ]
