# Generated by Django 4.0.2 on 2022-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateField(default='2008-01-01', verbose_name='发布日期'),
        ),
    ]
