# Generated by Django 4.0.2 on 2022-03-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
    ]
