# Generated by Django 4.0.2 on 2022-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_game_pic_remove_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pic',
            field=models.ImageField(default='image/1.jpg', upload_to='image'),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateField(default='2016-01-01 00:00:00'),
        ),
    ]
