# Generated by Django 4.0.2 on 2022-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_game_pic_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
